# Generated by Django 4.0.3 on 2022-04-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kryokart', '0002_alter_gps_latitude_alter_gps_longtitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='name',
            field=models.CharField(default='testdata', max_length=20),
            preserve_default=False,
        ),
    ]
