# Generated by Django 4.0.3 on 2022-04-25 22:40

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kryokart', '0003_gps_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='geodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
    ]
