# Generated by Django 4.0.3 on 2022-04-25 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kryokart', '0005_remove_geodata_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
