# Generated by Django 4.0.3 on 2022-04-25 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kryokart', '0006_geodata_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='position',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
