# Generated by Django 4.0.3 on 2022-04-26 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kryokart', '0007_geodata_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='geodata',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='name',
        ),
    ]
